global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['54.160.172.145:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['54.160.172.145:9100']
